export const countryCodes = [
	'AE', 'AF', 'AL', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BD', 'BE', 'BG', 'BH',
	'BO', 'BR', 'CA', 'CH', 'CL', 'CN', 'CO', 'CR', 'CU', 'CZ', 'DE', 'DK',
	'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'ET', 'FI', 'FR', 'GB', 'GE', 'GQ',
	'GR', 'GT', 'HK', 'HN', 'HR', 'HU', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IR',
	'IS', 'IT', 'JO', 'JP', 'KE', 'KH', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LK',
	'LT', 'LV', 'LY', 'MA', 'MK', 'MM', 'MN', 'MT', 'MX', 'MY', 'NG', 'NI',
	'NL', 'NO', 'NP', 'NZ', 'OM', 'PA', 'PE', 'PH', 'PL', 'PR', 'PT', 'PY',
	'QA', 'RO', 'RS', 'RU', 'SA', 'SE', 'SG', 'SI', 'SK', 'SO', 'SV', 'SY',
	'TH', 'TN', 'TR', 'TW', 'TZ', 'UA', 'US', 'UY', 'UZ', 'VE', 'VN', 'YE',
	'ZA', 'XX'
] as const

export type CountryCode = typeof countryCodes[number]

interface Lang
{
	name: string
	countryCode: CountryCode
	locale: string
}

export const langs: Lang[] = [
	{ name: 'Afrikaans', countryCode: 'ZA', locale: 'af-ZA' },
	{ name: 'Albanian', countryCode: 'AL', locale: 'sq-AL' },
	{ name: 'Amharic', countryCode: 'ET', locale: 'am-ET' },
	{ name: 'Arabic (Algeria)', countryCode: 'DZ', locale: 'ar-DZ' },
	{ name: 'Arabic (Bahrain)', countryCode: 'BH', locale: 'ar-BH' },
	{ name: 'Arabic (Egypt)', countryCode: 'EG', locale: 'ar-EG' },
	{ name: 'Arabic (Iraq)', countryCode: 'IQ', locale: 'ar-IQ' },
	{ name: 'Arabic (Jordan)', countryCode: 'JO', locale: 'ar-JO' },
	{ name: 'Arabic (Kuwait)', countryCode: 'KW', locale: 'ar-KW' },
	{ name: 'Arabic (Lebanon)', countryCode: 'LB', locale: 'ar-LB' },
	{ name: 'Arabic (Libya)', countryCode: 'LY', locale: 'ar-LY' },
	{ name: 'Arabic (Morocco)', countryCode: 'MA', locale: 'ar-MA' },
	{ name: 'Arabic (Oman)', countryCode: 'OM', locale: 'ar-OM' },
	{ name: 'Arabic (Qatar)', countryCode: 'QA', locale: 'ar-QA' },
	{ name: 'Arabic (Saudi Arabia)', countryCode: 'SA', locale: 'ar-SA' },
	{ name: 'Arabic (Syria)', countryCode: 'SY', locale: 'ar-SY' },
	{ name: 'Arabic (Tunisia)', countryCode: 'TN', locale: 'ar-TN' },
	{ name: 'Arabic (UAE)', countryCode: 'AE', locale: 'ar-AE' },
	{ name: 'Arabic (Yemen)', countryCode: 'YE', locale: 'ar-YE' },
	{ name: 'Azerbaijani', countryCode: 'AZ', locale: 'az-AZ' },
	{ name: 'Bangla', countryCode: 'BD', locale: 'bn-BD' },
	{ name: 'Bengali', countryCode: 'IN', locale: 'bn-IN' },
	{ name: 'Bosnian', countryCode: 'BA', locale: 'bs-BA' },
	{ name: 'Bulgarian', countryCode: 'BG', locale: 'bg-BG' },
	{ name: 'Burmese', countryCode: 'MM', locale: 'my-MM' },
	{ name: 'Catalan', countryCode: 'ES', locale: 'ca-ES' },
	{ name: 'Chinese (Cantonese, Traditional)', countryCode: 'HK', locale: 'zh-HK' },
	{ name: 'Chinese (Mandarin, Simplified)', countryCode: 'CN', locale: 'zh-CN' },
	{ name: 'Chinese (Taiwanese Mandarin, Traditional)', countryCode: 'TW', locale: 'zh-TW' },
	{ name: 'Croatian', countryCode: 'HR', locale: 'hr-HR' },
	{ name: 'Czech', countryCode: 'CZ', locale: 'cs-CZ' },
	{ name: 'Danish', countryCode: 'DK', locale: 'da-DK' },
	{ name: 'Dutch (Belgium)', countryCode: 'BE', locale: 'nl-BE' },
	{ name: 'Dutch (Netherlands)', countryCode: 'NL', locale: 'nl-NL' },
	{ name: 'English (Australia)', countryCode: 'AU', locale: 'en-AU' },
	{ name: 'English (Canada)', countryCode: 'CA', locale: 'en-CA' },
	{ name: 'English (Hong Kong)', countryCode: 'HK', locale: 'en-HK' },
	{ name: 'English (India)', countryCode: 'IN', locale: 'en-IN' },
	{ name: 'English (Ireland)', countryCode: 'IE', locale: 'en-IE' },
	{ name: 'English (Kenya)', countryCode: 'KE', locale: 'en-KE' },
	{ name: 'English (New Zealand)', countryCode: 'NZ', locale: 'en-NZ' },
	{ name: 'English (Nigeria)', countryCode: 'NG', locale: 'en-NG' },
	{ name: 'English (Phillipines)', countryCode: 'PH', locale: 'en-PH' },
	{ name: 'English (Singapore)', countryCode: 'SG', locale: 'en-SG' },
	{ name: 'English (South Africa)', countryCode: 'ZA', locale: 'en-ZA' },
	{ name: 'English (Tanzania)', countryCode: 'TZ', locale: 'en-TZ' },
	{ name: 'English (UK)', countryCode: 'GB', locale: 'en-GB' },
	{ name: 'English (US)', countryCode: 'US', locale: 'en-US' },
	{ name: 'Estonian', countryCode: 'EE', locale: 'et-EE' },
	{ name: 'Filipino', countryCode: 'PH', locale: 'fil-PH' },
	{ name: 'Finnish', countryCode: 'FI', locale: 'fi-FI' },
	{ name: 'French (Belgium)', countryCode: 'BE', locale: 'fr-BE' },
	{ name: 'French (Canada)', countryCode: 'CA', locale: 'fr-CA' },
	{ name: 'French (France)', countryCode: 'FR', locale: 'fr-FR' },
	{ name: 'French (Switzerland)', countryCode: 'CH', locale: 'fr-CH' },
	{ name: 'Galician', countryCode: 'ES', locale: 'gl-ES' },
	{ name: 'Georgian', countryCode: 'GE', locale: 'ka-GE' },
	{ name: 'German (Austria)', countryCode: 'AT', locale: 'de-AT' },
	{ name: 'German (Germany)', countryCode: 'DE', locale: 'de-DE' },
	{ name: 'German (Switzerland)', countryCode: 'CH', locale: 'de-CH' },
	{ name: 'Greek', countryCode: 'GR', locale: 'el-GR' },
	{ name: 'Gujarati', countryCode: 'IN', locale: 'gu-IN' },
	{ name: 'Hebrew', countryCode: 'IL', locale: 'he-IL' },
	{ name: 'Hindi', countryCode: 'IN', locale: 'hi-IN' },
	{ name: 'Hungarian', countryCode: 'HU', locale: 'hu-HU' },
	{ name: 'Icelandic', countryCode: 'IS', locale: 'is-IS' },
	{ name: 'Indonesian', countryCode: 'ID', locale: 'id-ID' },
	{ name: 'Irish', countryCode: 'IE', locale: 'ga-IE' },
	{ name: 'Italian', countryCode: 'IT', locale: 'it-IT' },
	{ name: 'Japanese', countryCode: 'JP', locale: 'ja-JP' },
	{ name: 'Javanese', countryCode: 'ID', locale: 'jv-ID' },
	{ name: 'Kannada', countryCode: 'IN', locale: 'kn-IN' },
	{ name: 'Kazakh', countryCode: 'KZ', locale: 'kk-KZ' },
	{ name: 'Khmer', countryCode: 'KH', locale: 'km-KH' },
	{ name: 'Korean', countryCode: 'KR', locale: 'ko-KR' },
	{ name: 'Lao', countryCode: 'LA', locale: 'lo-LA' },
	{ name: 'Latvian', countryCode: 'LV', locale: 'lv-LV' },
	{ name: 'Lithuanian', countryCode: 'LT', locale: 'lt-LT' },
	{ name: 'Macedonian', countryCode: 'MK', locale: 'mk-MK' },
	{ name: 'Malay', countryCode: 'MY', locale: 'ms-MY' },
	{ name: 'Malayalam', countryCode: 'IN', locale: 'ml-IN' },
	{ name: 'Maltese', countryCode: 'MT', locale: 'mt-MT' },
	{ name: 'Marathi', countryCode: 'IN', locale: 'mr-IN' },
	{ name: 'Mongolian', countryCode: 'MN', locale: 'mn-MN' },
	{ name: 'Nepali', countryCode: 'NP', locale: 'ne-NP' },
	{ name: 'Norwegian', countryCode: 'NO', locale: 'nb-NO' },
	{ name: 'Pashto', countryCode: 'AF', locale: 'ps-AF' },
	{ name: 'Persian', countryCode: 'IR', locale: 'fa-IR' },
	{ name: 'Polish', countryCode: 'PL', locale: 'pl-PL' },
	{ name: 'Portuguese (Brazil)', countryCode: 'BR', locale: 'pt-BR' },
	{ name: 'Portuguese (Portugal)', countryCode: 'PT', locale: 'pt-PT' },
	{ name: 'Romanian', countryCode: 'RO', locale: 'ro-RO' },
	{ name: 'Russian', countryCode: 'RU', locale: 'ru-RU' },
	{ name: 'Serbian', countryCode: 'RS', locale: 'sr-RS' },
	{ name: 'Sinhala', countryCode: 'LK', locale: 'si-LK' },
	{ name: 'Slovak', countryCode: 'SK', locale: 'sk-SK' },
	{ name: 'Slovenian', countryCode: 'SI', locale: 'sl-SI' },
	{ name: 'Somali', countryCode: 'SO', locale: 'so-SO' },
	{ name: 'Spanish (Argentina)', countryCode: 'AR', locale: 'es-AR' },
	{ name: 'Spanish (Bolivia)', countryCode: 'BO', locale: 'es-BO' },
	{ name: 'Spanish (Chile)', countryCode: 'CL', locale: 'es-CL' },
	{ name: 'Spanish (Colombia)', countryCode: 'CO', locale: 'es-CO' },
	{ name: 'Spanish (Costa Rica)', countryCode: 'CR', locale: 'es-CR' },
	{ name: 'Spanish (Cuba)', countryCode: 'CU', locale: 'es-CU' },
	{ name: 'Spanish (Dominican Republic)', countryCode: 'DO', locale: 'es-DO' },
	{ name: 'Spanish (Ecuador)', countryCode: 'EC', locale: 'es-EC' },
	{ name: 'Spanish (El Salvador)', countryCode: 'SV', locale: 'es-SV' },
	{ name: 'Spanish (Equatorial Guinea)', countryCode: 'GQ', locale: 'es-CQ' },
	{ name: 'Spanish (Guatemala)', countryCode: 'GT', locale: 'es-GT' },
	{ name: 'Spanish (Honduras)', countryCode: 'HN', locale: 'es-HN' },
	{ name: 'Spanish (Mexico)', countryCode: 'MX', locale: 'es-MX' },
	{ name: 'Spanish (Nicaragua)', countryCode: 'NI', locale: 'es-NI' },
	{ name: 'Spanish (Panama)', countryCode: 'PA', locale: 'es-PA' },
	{ name: 'Spanish (Paraguay)', countryCode: 'PY', locale: 'es-PY' },
	{ name: 'Spanish (Peru)', countryCode: 'PE', locale: 'es-PE' },
	{ name: 'Spanish (Puerto Rico)', countryCode: 'PR', locale: 'es-PR' },
	{ name: 'Spanish (Spain)', countryCode: 'ES', locale: 'es-ES' },
	{ name: 'Spanish (Uruguay)', countryCode: 'UY', locale: 'es-UY' },
	{ name: 'Spanish (US)', countryCode: 'US', locale: 'es-US' },
	{ name: 'Spanish (Venezuela)', countryCode: 'VE', locale: 'es-VE' },
	{ name: 'Sundanese', countryCode: 'ID', locale: 'su-ID' },
	{ name: 'Swahili (Kenya)', countryCode: 'KE', locale: 'sw-KE' },
	{ name: 'Swahili (Tanzania)', countryCode: 'TZ', locale: 'sw-TZ' },
	{ name: 'Swedish', countryCode: 'SE', locale: 'sv-SE' },
	{ name: 'Tamil (India)', countryCode: 'IN', locale: 'ta-IN' },
	{ name: 'Tamil (Malaysia)', countryCode: 'MY', locale: 'ta-MY' },
	{ name: 'Tamil (Singapore)', countryCode: 'SG', locale: 'ta-SG' },
	{ name: 'Tamil (Sri Lanka)', countryCode: 'LK', locale: 'ta-LK' },
	{ name: 'Telugu', countryCode: 'IN', locale: 'te-IN' },
	{ name: 'Thai', countryCode: 'TH', locale: 'th-TH' },
	{ name: 'Turkish', countryCode: 'TR', locale: 'tr-TR' },
	{ name: 'Ukrainian', countryCode: 'UA', locale: 'uk-UA' },
	{ name: 'Urdu', countryCode: 'IN', locale: 'ur-IN' },
	{ name: 'Uzbek', countryCode: 'UZ', locale: 'uz-UZ' },
	{ name: 'Vietnamese', countryCode: 'VN', locale: 'vi-VN' },
	{ name: 'Welsh', countryCode: 'GB', locale: 'cy-GB' },
	{ name: 'Zulu', countryCode: 'ZA', locale: 'zu-ZA' },
	{ name: 'Select', countryCode: 'XX', locale: 'xx-XX' }
]